name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
#ok
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

      TF_VAR_aws_region: us-east-1
      TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_ami: ${{ secrets.TF_VAR_AMI }}

    steps:
  - name: Check out repository
    uses: actions/checkout@v4

  - name: Run script in prod environment
    working-directory: ./environments/prod # or the full path
    run: |
      echo "Running in prod..."
        
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: |
          pwd
          ls -la
          find ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
